---
title: "NBA Project"
output: html_notebook
---

Initalize Packages
```{r}
library(dplyr)
library(tidyverse)
library(caret)
library(ggplot2)
library(GGally)
# install.packages('ggpmisc')
library(ggpmisc)
```

Steven took care of this through his python script:
  Learning Element 1: Grouping by different Information & Hardcode Categorical 
  Learning Element 2: Making linear model - finding best fit
  Learning Element 3: RMSE low as possible **You want: Lower RMSE, MAE, and higher R2**

Now, we need to answer the questions respectively 
```{r}
  NBA_Data <- NBA_Steven
  NBA_Data$exp_Sqrd = NBA_Data$exp ^ 2
  NBA_Data$salary_Log = log ( NBA_Data$salary )
  StevenForrester_Model <-
    lm( NBA_Data$salary_Log ~
          NBA_Data$team + NBA_Data$minutes_played + NBA_Data$defensive_rebound_percentage +
          NBA_Data$usage_percentage + NBA_Data$box_plus_minus + NBA_Data$exp + NBA_Data$exp_Sqrd ,
        data = NBA_Data
    )
    summary(StevenForrester_Model)
```

```{r}
  NBA_Data$SalaryPredict <- predict( StevenForrester_Model , data = NBA_Data )
  data.frame( R2 = R2 (NBA_Data$SalaryPredict, NBA_Data$salary_Log) , RMSE = RMSE (NBA_Data$SalaryPredict , NBA_Data$salary_Log), MAE = MAE (NBA_Data$SalaryPredict, NBA_Data$salary_Log))
```

```{r}
NBA_Subgroup <-
  subset(
      NBA_Data,
      index == 1373 | index == 1313 |index == 598 |index == 4359 |index == 1382 |index == 3488 | index == 2113 |index == 5131
  )

NBA_Subgroup$AbsDelta <- abs( NBA_Subgroup$SalaryPredict - NBA_Subgroup$salary_Log )
NBA_Subgroup$PercentChange <- ( NBA_Subgroup$AbsDelta / NBA_Subgroup$salary_Log )

view(NBA_Subgroup)

data.frame(
  Avg_AbsDelta = mean( NBA_Subgroup[["AbsDelta"]] ) ,
  Avg_PerChange = mean( NBA_Subgroup[["PercentChange"]] )
)
```


```{r}

##DO NOT RUN THIS CODE!
  #COEFFICIENTS 
    NBA_Graph_Coeff <- lm( NBA_Data$SalaryPredict ~ NBA_Data$salary_Log)
    # summary(NBA_Graph_Coeff)


  ggplot(
    NBA_Subgroup,
    aes(NBA_Subgroup$salary_Log, NBA_Subgroup$SalaryPredict )  
  ) + 
  geom_point(size=2) +
  #REGRESSION LINES
    geom_abline(
      intercept = NBA_Graph_Coeff$coefficients[1] ,
      slope = NBA_Graph_Coeff$coefficients[2]
    )
    # REGRESSION LINE - OPTION TWO
    # geom_smooth(method=lm, se=TRUE ) + 
  #FORMULA
    # stat_poly_eq(
    #   formula = y~x ,
    #   aes( label = paste(..eq.label.. , ..rr.label.., sep = "~~~") ),
    #   parse = TRUE
    # ) +
  #AXIS TITLES
    # xlab ( "Salary (log)" ) + ylab("Predicted Salary (log)")

```


**TRIAL GROUP -- UNLOGGING Salary**

```{r}
# NBA_Subgroup <-
#   subset(
#       NBA_Data,
#       index == 1373 | index == 1313 |index == 598 |index == 4359 |index == 1382 |index == 3488 | index == 2113 |index == 5131
#   )
# 

NBA_Subgroup$EXP_Sal <- exp ( NBA_Subgroup$salary_Log )
NBA_Subgroup$EXP_Sal_Pred <- exp ( NBA_Subgroup$SalaryPredict )
  
  
NBA_Subgroup$AbsDelta_1 <- abs( NBA_Subgroup$EXP_Sal_Pred - NBA_Subgroup$EXP_Sal )
NBA_Subgroup$PercentChange_1 <- ( NBA_Subgroup$AbsDelta_1 / NBA_Subgroup$EXP_Sal )

# view(NBA_Subgroup)

data.frame(
  Avg_AbsDelta = mean( NBA_Subgroup[["AbsDelta_1"]] ) ,
  Avg_PerChange = mean( NBA_Subgroup[["PercentChange_1"]] )
)
```


```{r}


  #COEFFICIENTS 
    NBA_Graph_Coeff <- lm( NBA_Data$SalaryPredict ~ NBA_Data$salary_Log)


  ggplot(
    NBA_Subgroup,
    aes(NBA_Subgroup$EXP_Sal, NBA_Subgroup$EXP_Sal_Pred )  
  ) + 
  geom_point(size=2) +
  # geom_smooth(method=lm, se=TRUE ) + 
  #REGRESSION LINES
    geom_abline(
      intercept = NBA_Graph_Coeff$coefficients[1] ,
      slope = NBA_Graph_Coeff$coefficients[2]
    ) + 
  #FORMULA
  stat_poly_eq(
    formula = NBA_Graph_Coeff , #y~x ,
    aes( label = paste(..eq.label.. , ..rr.label.., sep = "~~~") ),
    parse = TRUE
  ) +
  #AXIS TITLES
  xlab ( "Salary" ) + ylab("Predicted Salary")

```